---
name: Feature Request
description: Propose a new feature or enhancement for FoundationsOS
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Target Component
      options:
        - Security (TPM2 / OP-TEE / TF-A)
        - OTA Update (RAUC)
        - Init System (systemd)
        - Linux Kernel / Buildroot
        - Disk Encryption
        - Network / Firewall
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered

  - type: checkboxes
    id: willing-to-pr
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a pull request for this feature
